package sm.dao;

import sm.pojo.NoveSendaddr;

public interface NoveSendaddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sendaddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    int insert(NoveSendaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    int insertSelective(NoveSendaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    NoveSendaddr selectByPrimaryKey(Integer sendaddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveSendaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_sendaddr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveSendaddr record);
}