package sm.dao;

import sm.pojo.NoveGoodsSize;

public interface NoveGoodsSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    int insert(NoveGoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    int insertSelective(NoveGoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    NoveGoodsSize selectByPrimaryKey(Integer sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveGoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_goodssize
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveGoodsSize record);
}