package sm.dao;

import sm.pojo.NoveCatgSecond;

public interface NoveCatgSecondMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer catgsecondId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    int insert(NoveCatgSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    int insertSelective(NoveCatgSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    NoveCatgSecond selectByPrimaryKey(Integer catgsecondId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveCatgSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_catgsecond
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveCatgSecond record);
}