package sm.dao;

import sm.pojo.NoveOrderGoods;

public interface NoveOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    int insert(NoveOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    int insertSelective(NoveOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    NoveOrderGoods selectByPrimaryKey(Integer orderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveOrderGoods record);
}