package sm.dao;

import sm.pojo.NoveAdmin;

public interface NoveAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    int insert(NoveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    int insertSelective(NoveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    NoveAdmin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveAdmin record);
}