package sm.dao;

import sm.pojo.NoveOrderStatus;

public interface NoveOrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderstatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    int insert(NoveOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    int insertSelective(NoveOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    NoveOrderStatus selectByPrimaryKey(Integer orderstatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orderstatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveOrderStatus record);
}