package sm.dao;

import sm.pojo.NoveCollection;

public interface NoveCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    int insert(NoveCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    int insertSelective(NoveCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    NoveCollection selectByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveCollection record);
}