package sm.pojo;

public class NoveGoodsSize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goodssize.size_id
     *
     * @mbggenerated
     */
    private Integer sizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goodssize.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goodssize.goods_price
     *
     * @mbggenerated
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goodssize.goods_size
     *
     * @mbggenerated
     */
    private String goodsSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goodssize.size_id
     *
     * @return the value of nove_goodssize.size_id
     *
     * @mbggenerated
     */
    public Integer getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goodssize.size_id
     *
     * @param sizeId the value for nove_goodssize.size_id
     *
     * @mbggenerated
     */
    public void setSizeId(Integer sizeId) {
        this.sizeId = sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goodssize.goodsId
     *
     * @return the value of nove_goodssize.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goodssize.goodsId
     *
     * @param goodsid the value for nove_goodssize.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goodssize.goods_price
     *
     * @return the value of nove_goodssize.goods_price
     *
     * @mbggenerated
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goodssize.goods_price
     *
     * @param goodsPrice the value for nove_goodssize.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goodssize.goods_size
     *
     * @return the value of nove_goodssize.goods_size
     *
     * @mbggenerated
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goodssize.goods_size
     *
     * @param goodsSize the value for nove_goodssize.goods_size
     *
     * @mbggenerated
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize == null ? null : goodsSize.trim();
    }
}