package sm.pojo;

public class NoveUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_user.user_addr
     *
     * @mbggenerated
     */
    private String userAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_user.user_tel
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_user.user_id
     *
     * @return the value of nove_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_user.user_id
     *
     * @param userId the value for nove_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_user.user_name
     *
     * @return the value of nove_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_user.user_name
     *
     * @param userName the value for nove_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_user.password
     *
     * @return the value of nove_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_user.password
     *
     * @param password the value for nove_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_user.user_addr
     *
     * @return the value of nove_user.user_addr
     *
     * @mbggenerated
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_user.user_addr
     *
     * @param userAddr the value for nove_user.user_addr
     *
     * @mbggenerated
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr == null ? null : userAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_user.user_tel
     *
     * @return the value of nove_user.user_tel
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_user.user_tel
     *
     * @param userTel the value for nove_user.user_tel
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }
}