package sm.pojo;

public class NoveSendaddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_id
     *
     * @mbggenerated
     */
    private Integer sendaddrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_addr
     *
     * @mbggenerated
     */
    private String sendaddrAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_tel
     *
     * @mbggenerated
     */
    private String sendaddrTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_zipCode
     *
     * @mbggenerated
     */
    private String sendaddrZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_deleteStatus
     *
     * @mbggenerated
     */
    private Integer sendaddrDeletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_sendaddr.sendaddr_defaultStatus
     *
     * @mbggenerated
     */
    private Integer sendaddrDefaultstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_id
     *
     * @return the value of nove_sendaddr.sendaddr_id
     *
     * @mbggenerated
     */
    public Integer getSendaddrId() {
        return sendaddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_id
     *
     * @param sendaddrId the value for nove_sendaddr.sendaddr_id
     *
     * @mbggenerated
     */
    public void setSendaddrId(Integer sendaddrId) {
        this.sendaddrId = sendaddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_addr
     *
     * @return the value of nove_sendaddr.sendaddr_addr
     *
     * @mbggenerated
     */
    public String getSendaddrAddr() {
        return sendaddrAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_addr
     *
     * @param sendaddrAddr the value for nove_sendaddr.sendaddr_addr
     *
     * @mbggenerated
     */
    public void setSendaddrAddr(String sendaddrAddr) {
        this.sendaddrAddr = sendaddrAddr == null ? null : sendaddrAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_tel
     *
     * @return the value of nove_sendaddr.sendaddr_tel
     *
     * @mbggenerated
     */
    public String getSendaddrTel() {
        return sendaddrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_tel
     *
     * @param sendaddrTel the value for nove_sendaddr.sendaddr_tel
     *
     * @mbggenerated
     */
    public void setSendaddrTel(String sendaddrTel) {
        this.sendaddrTel = sendaddrTel == null ? null : sendaddrTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_zipCode
     *
     * @return the value of nove_sendaddr.sendaddr_zipCode
     *
     * @mbggenerated
     */
    public String getSendaddrZipcode() {
        return sendaddrZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_zipCode
     *
     * @param sendaddrZipcode the value for nove_sendaddr.sendaddr_zipCode
     *
     * @mbggenerated
     */
    public void setSendaddrZipcode(String sendaddrZipcode) {
        this.sendaddrZipcode = sendaddrZipcode == null ? null : sendaddrZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_deleteStatus
     *
     * @return the value of nove_sendaddr.sendaddr_deleteStatus
     *
     * @mbggenerated
     */
    public Integer getSendaddrDeletestatus() {
        return sendaddrDeletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_deleteStatus
     *
     * @param sendaddrDeletestatus the value for nove_sendaddr.sendaddr_deleteStatus
     *
     * @mbggenerated
     */
    public void setSendaddrDeletestatus(Integer sendaddrDeletestatus) {
        this.sendaddrDeletestatus = sendaddrDeletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_sendaddr.sendaddr_defaultStatus
     *
     * @return the value of nove_sendaddr.sendaddr_defaultStatus
     *
     * @mbggenerated
     */
    public Integer getSendaddrDefaultstatus() {
        return sendaddrDefaultstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_sendaddr.sendaddr_defaultStatus
     *
     * @param sendaddrDefaultstatus the value for nove_sendaddr.sendaddr_defaultStatus
     *
     * @mbggenerated
     */
    public void setSendaddrDefaultstatus(Integer sendaddrDefaultstatus) {
        this.sendaddrDefaultstatus = sendaddrDefaultstatus;
    }
}