package sm.pojo;

import java.util.Date;

public class NoveGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_pic
     *
     * @mbggenerated
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_area
     *
     * @mbggenerated
     */
    private String goodsArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_sizeId
     *
     * @mbggenerated
     */
    private Integer goodsSizeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_showStatus
     *
     * @mbggenerated
     */
    private Integer goodsShowstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_shelfTime
     *
     * @mbggenerated
     */
    private Date goodsShelftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_count
     *
     * @mbggenerated
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_goods.goods_descript
     *
     * @mbggenerated
     */
    private String goodsDescript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_id
     *
     * @return the value of nove_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_id
     *
     * @param goodsId the value for nove_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_name
     *
     * @return the value of nove_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_name
     *
     * @param goodsName the value for nove_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_pic
     *
     * @return the value of nove_goods.goods_pic
     *
     * @mbggenerated
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_pic
     *
     * @param goodsPic the value for nove_goods.goods_pic
     *
     * @mbggenerated
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_area
     *
     * @return the value of nove_goods.goods_area
     *
     * @mbggenerated
     */
    public String getGoodsArea() {
        return goodsArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_area
     *
     * @param goodsArea the value for nove_goods.goods_area
     *
     * @mbggenerated
     */
    public void setGoodsArea(String goodsArea) {
        this.goodsArea = goodsArea == null ? null : goodsArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_sizeId
     *
     * @return the value of nove_goods.goods_sizeId
     *
     * @mbggenerated
     */
    public Integer getGoodsSizeid() {
        return goodsSizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_sizeId
     *
     * @param goodsSizeid the value for nove_goods.goods_sizeId
     *
     * @mbggenerated
     */
    public void setGoodsSizeid(Integer goodsSizeid) {
        this.goodsSizeid = goodsSizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_showStatus
     *
     * @return the value of nove_goods.goods_showStatus
     *
     * @mbggenerated
     */
    public Integer getGoodsShowstatus() {
        return goodsShowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_showStatus
     *
     * @param goodsShowstatus the value for nove_goods.goods_showStatus
     *
     * @mbggenerated
     */
    public void setGoodsShowstatus(Integer goodsShowstatus) {
        this.goodsShowstatus = goodsShowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_shelfTime
     *
     * @return the value of nove_goods.goods_shelfTime
     *
     * @mbggenerated
     */
    public Date getGoodsShelftime() {
        return goodsShelftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_shelfTime
     *
     * @param goodsShelftime the value for nove_goods.goods_shelfTime
     *
     * @mbggenerated
     */
    public void setGoodsShelftime(Date goodsShelftime) {
        this.goodsShelftime = goodsShelftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_count
     *
     * @return the value of nove_goods.goods_count
     *
     * @mbggenerated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_count
     *
     * @param goodsCount the value for nove_goods.goods_count
     *
     * @mbggenerated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_goods.goods_descript
     *
     * @return the value of nove_goods.goods_descript
     *
     * @mbggenerated
     */
    public String getGoodsDescript() {
        return goodsDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_goods.goods_descript
     *
     * @param goodsDescript the value for nove_goods.goods_descript
     *
     * @mbggenerated
     */
    public void setGoodsDescript(String goodsDescript) {
        this.goodsDescript = goodsDescript == null ? null : goodsDescript.trim();
    }
}