package sm.pojo;

public class NoveCatg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_catg.catg_id
     *
     * @mbggenerated
     */
    private Integer catgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_catg.catg_name
     *
     * @mbggenerated
     */
    private String catgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_catg.catg_id
     *
     * @return the value of nove_catg.catg_id
     *
     * @mbggenerated
     */
    public Integer getCatgId() {
        return catgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_catg.catg_id
     *
     * @param catgId the value for nove_catg.catg_id
     *
     * @mbggenerated
     */
    public void setCatgId(Integer catgId) {
        this.catgId = catgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_catg.catg_name
     *
     * @return the value of nove_catg.catg_name
     *
     * @mbggenerated
     */
    public String getCatgName() {
        return catgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_catg.catg_name
     *
     * @param catgName the value for nove_catg.catg_name
     *
     * @mbggenerated
     */
    public void setCatgName(String catgName) {
        this.catgName = catgName == null ? null : catgName.trim();
    }
}