package sm.pojo;

import java.util.Date;

public class NoveOrders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.order_date
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.order_price
     *
     * @mbggenerated
     */
    private Double orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.sendaddrId
     *
     * @mbggenerated
     */
    private Integer sendaddrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.deleteStatus
     *
     * @mbggenerated
     */
    private Integer deletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_orders.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.order_id
     *
     * @return the value of nove_orders.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.order_id
     *
     * @param orderId the value for nove_orders.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.order_date
     *
     * @return the value of nove_orders.order_date
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.order_date
     *
     * @param orderDate the value for nove_orders.order_date
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.order_price
     *
     * @return the value of nove_orders.order_price
     *
     * @mbggenerated
     */
    public Double getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.order_price
     *
     * @param orderPrice the value for nove_orders.order_price
     *
     * @mbggenerated
     */
    public void setOrderPrice(Double orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.userId
     *
     * @return the value of nove_orders.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.userId
     *
     * @param userid the value for nove_orders.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.sendaddrId
     *
     * @return the value of nove_orders.sendaddrId
     *
     * @mbggenerated
     */
    public Integer getSendaddrid() {
        return sendaddrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.sendaddrId
     *
     * @param sendaddrid the value for nove_orders.sendaddrId
     *
     * @mbggenerated
     */
    public void setSendaddrid(Integer sendaddrid) {
        this.sendaddrid = sendaddrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.deleteStatus
     *
     * @return the value of nove_orders.deleteStatus
     *
     * @mbggenerated
     */
    public Integer getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.deleteStatus
     *
     * @param deletestatus the value for nove_orders.deleteStatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_orders.order_status
     *
     * @return the value of nove_orders.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_orders.order_status
     *
     * @param orderStatus the value for nove_orders.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }
}