package sm.pojo;

public class NoveCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_collection.collection_id
     *
     * @mbggenerated
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_collection.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_collection.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_collection.collection_id
     *
     * @return the value of nove_collection.collection_id
     *
     * @mbggenerated
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_collection.collection_id
     *
     * @param collectionId the value for nove_collection.collection_id
     *
     * @mbggenerated
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_collection.goodsId
     *
     * @return the value of nove_collection.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_collection.goodsId
     *
     * @param goodsid the value for nove_collection.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_collection.userId
     *
     * @return the value of nove_collection.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_collection.userId
     *
     * @param userid the value for nove_collection.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}