package sm.pojo;

import java.util.Date;

public class NoveComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.comment_time
     *
     * @mbggenerated
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.comment_score
     *
     * @mbggenerated
     */
    private Integer commentScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.comment_pic
     *
     * @mbggenerated
     */
    private String commentPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_comment.comment_detaile
     *
     * @mbggenerated
     */
    private String commentDetaile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.comment_id
     *
     * @return the value of nove_comment.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.comment_id
     *
     * @param commentId the value for nove_comment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.comment_time
     *
     * @return the value of nove_comment.comment_time
     *
     * @mbggenerated
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.comment_time
     *
     * @param commentTime the value for nove_comment.comment_time
     *
     * @mbggenerated
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.comment_score
     *
     * @return the value of nove_comment.comment_score
     *
     * @mbggenerated
     */
    public Integer getCommentScore() {
        return commentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.comment_score
     *
     * @param commentScore the value for nove_comment.comment_score
     *
     * @mbggenerated
     */
    public void setCommentScore(Integer commentScore) {
        this.commentScore = commentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.comment_pic
     *
     * @return the value of nove_comment.comment_pic
     *
     * @mbggenerated
     */
    public String getCommentPic() {
        return commentPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.comment_pic
     *
     * @param commentPic the value for nove_comment.comment_pic
     *
     * @mbggenerated
     */
    public void setCommentPic(String commentPic) {
        this.commentPic = commentPic == null ? null : commentPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.userId
     *
     * @return the value of nove_comment.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.userId
     *
     * @param userid the value for nove_comment.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.goodsId
     *
     * @return the value of nove_comment.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.goodsId
     *
     * @param goodsid the value for nove_comment.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_comment.comment_detaile
     *
     * @return the value of nove_comment.comment_detaile
     *
     * @mbggenerated
     */
    public String getCommentDetaile() {
        return commentDetaile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_comment.comment_detaile
     *
     * @param commentDetaile the value for nove_comment.comment_detaile
     *
     * @mbggenerated
     */
    public void setCommentDetaile(String commentDetaile) {
        this.commentDetaile = commentDetaile == null ? null : commentDetaile.trim();
    }
}