package sm.pojo;

public class NoveCatgSecond {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_catgsecond.catgSecond_id
     *
     * @mbggenerated
     */
    private Integer catgsecondId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_catgsecond.catgId
     *
     * @mbggenerated
     */
    private Integer catgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nove_catgsecond.catgSecond_name
     *
     * @mbggenerated
     */
    private String catgsecondName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_catgsecond.catgSecond_id
     *
     * @return the value of nove_catgsecond.catgSecond_id
     *
     * @mbggenerated
     */
    public Integer getCatgsecondId() {
        return catgsecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_catgsecond.catgSecond_id
     *
     * @param catgsecondId the value for nove_catgsecond.catgSecond_id
     *
     * @mbggenerated
     */
    public void setCatgsecondId(Integer catgsecondId) {
        this.catgsecondId = catgsecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_catgsecond.catgId
     *
     * @return the value of nove_catgsecond.catgId
     *
     * @mbggenerated
     */
    public Integer getCatgid() {
        return catgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_catgsecond.catgId
     *
     * @param catgid the value for nove_catgsecond.catgId
     *
     * @mbggenerated
     */
    public void setCatgid(Integer catgid) {
        this.catgid = catgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nove_catgsecond.catgSecond_name
     *
     * @return the value of nove_catgsecond.catgSecond_name
     *
     * @mbggenerated
     */
    public String getCatgsecondName() {
        return catgsecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nove_catgsecond.catgSecond_name
     *
     * @param catgsecondName the value for nove_catgsecond.catgSecond_name
     *
     * @mbggenerated
     */
    public void setCatgsecondName(String catgsecondName) {
        this.catgsecondName = catgsecondName == null ? null : catgsecondName.trim();
    }
}